version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - aiops-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    networks:
      - aiops-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - aiops-net
    restart: unless-stopped

networks:
  aiops-net:
    driver: bridge